### ISSUE TITLE
DNU doesn't run on coreclr on *nix/OSX

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx#1793]
This is a work item to track the progress on that feature.

- [x] URI class doesn't handle file paths correctly (DNX PR: #1691 or corefx issue: https://github.com/dotnet/corefx/issues/1745)
- [x] Need proper check for OS and Mono (#1692)
- [x] Restore hangs with more than a couple concurrent requests (https://github.com/dotnet/corefx/issues?q=is%3Aissue+is%3Aopen+Implement+Unix+label%3ASystem.Net)
- [x] DNU doesn't get correct local app data folder on *nix with CoreCLR (https://github.com/aspnet/dnx/issues/1813)
- [x] Don't use Console.GetColor (#1724)
- [ ] NuGet-related paths/files should be case-sensitively consistent (#2270)
- [x] CoreCLR HttpClient is not functional on *nix (https://github.com/dotnet/corefx/issues/2480)

**Comment by colemickens** [comment]
1.0.0-beta5-11722 status for `dnu restore` under Ubuntu:

```
----------
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at NuGet.Settings.LoadDefaultSettings(IFileSystem fileSystem, String configFileName, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.SettingsUtils.ReadSettings(String solutionDir, String nugetConfigFile, IFileSystem fileSystem, IMachineWideSettings machineWideSettings)
   at Microsoft.Framework.PackageManager.RestoreCommand.ReadSettings(String solutionDirectory)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__68.MoveNext()
----------
Restore failed
Value cannot be null.
Parameter name: path1
```

**Comment by BrennanConroy** [comment]
The above error is because NuGet uses Environment Variables that don't have values on non-windows OS's. Tracked by: https://github.com/NuGet/Home/issues/472

**Comment by muratg** [comment]
@BrennanConroy Can you update the checklist to reflect the current state?

**Comment by akamud** [comment]
Any update on this?

**Comment by overeemm** [comment]
Because of this, the whole getting started on macosx (http://dotnet.github.io/core/getting-started/) is broken, right?

**Comment by colemickens** [comment]
Those instructions seem to guide the user into use dnx-mono to restore packages and then switch back to dnx-coreclr for actual execution (which has worked empirically for me)... but it doesn't include the instructions to actually install dnx-mono latest, only instructions for install dnx-coreclr latest.

**Comment by overeemm** [comment]
@colemickens thanks, that worked :)

**Comment by muratg** [comment]
@BrennanConroy Do we have a bug on `Restore hangs with more than a couple concurrent requests (investigating)` item on the CoreCLR side?  Main Beta 7 theme is cross plat so we'll need to move forward with this.

cc @danroth27

**Comment by BrennanConroy** [comment]
I don't think so. We have an email thread with them.

**Comment by muratg** [comment]
Can we file a bug to track it and add the bug number to the list?  Thanks.

**Comment by IRooc** [comment]
Seems like since ```1.0.0-beta7-12290``` the dnx . kestrel on a coreclr target does nothing anymore on a Mac and linux.

**Comment by BrennanConroy** [comment]
Fixed with https://github.com/aspnet/dnx/pull/2397

**Comment by IRooc** [comment]
@BrennanConroy thanks, any idea how I can see on which version the issue #2397 will be available?

**Comment by BrennanConroy** [comment]
The next version of dnx after 12302

**Comment by IRooc** [comment]
Tried ```dnx . kestrel``` on coreclr version beta7-12321 on a mac but still it returns to the prompt immediately without any output. 

```dnx --h``` says ```Trace/BPT trap: 5```

**Comment by BrennanConroy** [comment]
Sorry, I fixed the breaking change to version 12302 but then another breaking change came in. I'll be fixing it and trying to get a build out soon.

**Comment by IRooc** [comment]
No problem. Thanks for this all!

**Comment by IRooc** [comment]
Just a bump but running either ```dnu restore``` or ```dnx kestrel``` on **1.0.0-beta8-15120** coreclr x64 on mac still just outputs Trace/BPT trap: 5 at the commandline when tried with the aspnet/Home samples

**Comment by BrennanConroy** [comment]
If you're using beta8 use 15138 or later

**Comment by BrennanConroy** [comment]
Dnu on Xplat CoreCLR is working, we will still be tracking ```NuGet-related paths/files should be case-sensitively consistent (#2270)```

**Comment by Grochni** [comment]
@BrennanConroy  I'm using 1.0.0-beta8-155530 and I'm still only seeing `Trace/BPT trap: 5` when running `dnu restore`

**Comment by IRooc** [comment]
@Grochni according to a comment here https://github.com/aspnet/dnx/issues/2580 the 15530 was a bad build. We'll have to wait for a newer one.

**Comment by colemickens** [comment]
15509 was working for me, but 15545 is having issues:

```
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'libcurl' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
```
